// This file is auto-generated from config.toml
// Do not edit this file directly
export const tomlConfig = {
  "site": {
    "title": "Laplace",
    "subtitle": "Blog",
    "lang": "zh_CN",
    "url": "https://127.0.0.1:4321",
    "themeColor": {
      "hue": 250,
      "fixed": false
    },
    "banner": {
      "enable": false,
      "src": "assets/images/demo-banner.png",
      "position": "center",
      "credit": {
        "enable": false,
        "text": "",
        "url": ""
      }
    },
    "toc": {
      "enable": true,
      "depth": 4
    },
    "favicon": []
  },
  "navBar": {
    "links": [
      0,
      1,
      2,
      3,
      {
        "name": "GitHub",
        "url": "https://github.com/laplace825",
        "external": true
      }
    ]
  },
  "profile": {
    "avatar": "assets/images/avatar.png",
    "name": "Laplace",
    "bio": "「0」が過去で 「1」が未来. 🌟",
    "links": [
      {
        "name": "Telegram",
        "icon": "fa6-brands:telegram",
        "url": "https://t.me/laplace_he"
      },
      {
        "name": "GitHub",
        "icon": "fa6-brands:github",
        "url": "https://github.com/laplace825"
      },
      {
        "name": "Email",
        "icon": "material-symbols:mail-rounded",
        "url": "mailto:laplace.he@outlook.com"
      }
    ]
  },
  "license": {
    "enable": true,
    "name": "CC BY-NC-SA 4.0",
    "url": "https://creativecommons.org/licenses/by-nc-sa/4.0/"
  },
  "expressiveCode": {
    "theme": "catppuccin-mocha"
  },
  "friendLinks": {
    "enable": true,
    "links": [
      {
        "name": "Qlexander",
        "description": "Vanitas Vanitatum Et Omnia Vanitas",
        "avatar": "https://s2.loli.net/2024/10/21/DwQyKdZoslihtUS.png",
        "url": "https://qlexander.cn"
      },
      {
        "name": "Ray",
        "description": "ENDsoft's Blog",
        "avatar": "https://r-ay.cn/images/cb254102-aa64-4051-af5f-77a325f14ff7.png",
        "url": "https://blog.r-ay.cn/"
      }
    ]
  }
};
